name: PR Labels

on: [pull_request_target]

jobs:
  size-labels:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: learningequality/pr-labeler@4fa65192c29ab023b135421c19bb4aa63f39df27
        with:
          xs_max_size: '10'
          s_max_size: '100'
          m_max_size: '500'
          l_max_size: '1000'
          exclude_files: '^$'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  other-labels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
